---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
   ingress.bluemix.net/redirect-to-https: "True"
#   {{- if .Values.appid_credentials }}
#   ingress.bluemix.net/appid-auth: "bindSecret={{- .Release.Name -}}-appid namespace={{.Release.Namespace}} requestType=web serviceName={{ .Release.Name }}-todo-frontend idToken=true"
#   {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Release.Name }}.{{ .Values.ingressSubdomain }}
    secretName: {{ .Values.ingressSecret }}
  rules:
  - host: {{ .Release.Name }}.{{ .Values.ingressSubdomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-todo-frontend
          servicePort: 8888
