---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
   ingress.bluemix.net/redirect-to-https: "True"
spec:
  tls:
  - hosts:
    - {{ .Release.Name }}.{{ .Values.ingressSubdomain }}
    secretName: {{ .Values.ingressSecret }}
  rules:
  - host: {{ .Release.Name }}.{{ .Values.ingressSubdomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-todo-frontend
          servicePort: 8888
