---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-mongodb-backend
spec:
  selector:
    app: {{ .Release.Name }}-mongodb-backend
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-todo-backend
spec:
  selector:
    app: {{ .Release.Name }}-todo-backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-todo-frontend
spec:
  selector:
    app: {{ .Release.Name }}-todo-frontend
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
