apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: simpleapp-placementrule
  labels:
    app: simpleapp
spec:
  clusterReplicas: 1
  clusterLabels:
    matchLabels:  
      cloud: IBM
      vendor: IKS
      region: EU

